[package]
name = "openphoto-raster"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
openphoto-geom = { workspace = true }
openphoto-color = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
