[package]
name = "openphoto-compose"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
openphoto-geom = { workspace = true }
openphoto-color = { workspace = true }
openphoto-raster = { workspace = true }
openphoto-doc = { workspace = true }
openphoto-vector = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }
openphoto-paint = { workspace = true }

[[bench]]
name = "compose"
harness = false
