[package]
name = "openphoto-paint"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
openphoto-geom = { workspace = true }
openphoto-color = { workspace = true }
openphoto-raster = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
